### PR TITLE
Remove Encodable example

### PR DESCRIPTION
**Pull request by KodrAus**
I haven't found a decent alternative from a quick poke around yet so I thought I'd just remove the `Encodable` example. I don't think it adds a whole lot of value over the `Hash` one since they look quite similar.

### CODE REVIEW

**Comment by KodrAus** [comment]
cc: @elahn

**Comment by elahn** [comment]
Yeah, I agree. The only thing it's showing is that it works with tuple structs, but that could be added to the text.

**Comment by KodrAus** [comment]
It looks like we do still have an example of a tuple struct under the _Delegating inherent methods_ section.

**Comment by elahn** [comment]
Good point. 👍

**Pull request merged**
